---
# operator-container-images-curator role defaults

acs_registry_port: 5000
acs_internal_registry: "{{ ansible_facts['fqdn'] }}:{{ registry_port }}/"
acs_org_name: "operator-containers"
acs_operator_containers_target_count: 50
