# optional
# count: 1
---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: load-sctp-module
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
        - path: /etc/modprobe.d/sctp-blacklist.conf
          contents:
            source: data:,
            verification: {}
          filesystem: root
          mode: 420
        - path: /etc/modules-load.d/sctp-load.conf
          contents:
            source: data:,sctp
          mode: 420
