---
# Playbook to Cleanup ACS Sensors from ACM Managed Clusters
# Note: This playbook assumes you have sensor directories in /root/secured_clusters/sensor-<cluster-name>/
#
# Example Usage:
#
# time ansible-playbook -i ansible/inventory/cloud30.local ansible/acs-spokes-sensor-cleanup.yml
# time ansible-playbook -i ansible/inventory/cloud30.local ansible/acs-spokes-sensor-cleanup.yml -e cleanup_sensor_generation_after_delete=true
#
- name: Cleanup ACS sensors from managed clusters
  hosts: bastion 
  connection: local
  gather_facts: true

  vars_files:
  - vars/all.yml

  roles:
    - acs-spokes-sensor-cleanup
